# Site settings
title:          Naveen Bhatia
description:    "Learn. Work. Share"
baseurl:        ""
url:            "https://nbhatia.github.io"

# Google Analytics
google_analytics: G-NPX7YK1R4X

# Author
author:
  name:         Naveen Bhatia
  url:          https://nbhatia.github.io
  email:        naveen.bhatia.in@gmail.co.in

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - TBD: add a plugin for search support
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         nbhatia-github-io
